#!/bin/sh

# AnyCast Controller Daemon Init Script
# Add this file with the Filer package
# File: /usr/local/etc/rc.d/anycast_ctrld
# Description: AnyCast Controller Daemon Init Script
# Permission: 755
# Script/Command: 
# Execute mode: Background

name="anycast_ctrld"
interpreter="/usr/local/bin/${name}"
script="${interpreter}.sh"
pidfile="/var/run/${name}.pid"
log_file="/var/log/${name}.log"

# Function to log messages
log_message() {
    /usr/bin/logger -p daemon.info -t "$name" "$1"
}

# Function to check and copy the shell
check_shell() {
    if [ ! -f "$interpreter" ]; then
        cp -p "$(which sh)" "$interpreter" || { log_message "Failed to copy shell. Exiting..."; exit 1; }
        log_message "Shell copied successfully."
    else
        log_message "Shell already exists."
    fi
}

# Function to start the daemon
rc_start() {
    rc_stop
    (exec "$interpreter" "$script" & echo $! > "$pidfile")
    log_message "Daemon started."
}

# Function to stop the daemon
rc_stop() {
    if [ -f "$pidfile" ]; then
        kill -9 $(cat "$pidfile") >&2 || true
        rm -f "$pidfile"
        log_message "Daemon stopped."
    else
        log_message "Daemon is not running."
    fi
}

# Check the command line argument and perform the corresponding action
case "$1" in
    start)
        check_shell
        rc_start
        ;;
    stop)
        rc_stop
        ;;
    restart)
        check_shell
        rc_stop
        rc_start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
